### PR TITLE
Frontend: UI Improvement.

### PR DESCRIPTION
**Pull request by Smitkhobragade**
- Dark Theme Implementation: Introduced a dark theme with a subtle gradient for a modern, clean look and enhanced visual comfort for nighttime use.
- Prominent Header: Added a clear "Helpmate AI" heading at the top of the application to establish brand identity.
- Clear Call to Action (CTA): Redesigned the "Generate Answer" button to be the primary call to action, using a contrasting color and rounded shape for better visibility.
- Mobile-First Design Approach: Adopted a mobile-first approach to ensure a smooth user experience across all device sizes, designing the layout to adapt effectively to larger screens.
- Well-Defined Footer: Created a visually appealing and informative footer for enhanced navigation and branding.
- Smooth Transitions: Implemented smooth transitions throughout the application for a polished, professional feel.
- Animations: Added animations for the send button and microphone button to provide visual feedback during user interactions.

### CODE REVIEW

**Comment by codeaashu** [comment]
Screenshot_2024-10-30-17-17-32-07_40deb401b9ffe8e1df2f1cc5ba480b12


🌟 It's not responsive on mobile view when we going to generate a code I think you use a slider to solve this  -- so, Make it better 👆🏻


🌟 Also  check out PR #15 👇🏻
& Add a feature to show the previous prompt history ( question and answer both )

Just like this image 👇🏻

IMG-20241030-WA0009

Apart from that all things is ok Just solve this two issues 
& I will merged your code 


And I have something special offer for you 💌

**Comment by Smitkhobragade** [comment]
@codeaashu . I have done the changes as per stated in above discussion.

**Comment by Smitkhobragade** [comment]
@codeaashu what is the special offer for me ?

**Comment by Smitkhobragade** [comment]
@codeaashu Any reviews ??

**Comment by codeaashu** [comment]
check out your mail

**Pull request merged**
